# Generated by Django 3.2.7 on 2021-11-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_meetup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
